{
    'name': "Retail Defaults",
    'version': "16.0.1.0,0",
    'summary': """""",
    'description': """""",
    'category': 'Retail',
    'author': "Zillo Tech",
    'company': "Zillo WebTech",
    'maintainer': "Zillo WebTech",
    'website': "https://www.nckwebtech.com/",
    'depends': ['contacts', 'sale', 'sale_management', 'sale_stock', 'purchase', 'mrp', 'delivery'],
    'data': ['reports/report_template.xml',
             'reports/purchase_reports.xml',
             'views/default_cag_views.xml',
             'views/mrp_view.xml', ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [],
    },
    'images': ['static/description/banner.png'],
    'license': "AGPL-3",
    'installable': True,
    'application': True,
    'price': 78.50,
    'currency': 'USD',
}
