{
    'name': 'USA Sale Tax Install',
    'version': '16.0.1.0.0',
    'summary': 'USA Sale Tax Table Installation',
    'sequence': 10,
    'description': """""",
    'category': 'Accounting/Accounting',
    'author': 'Zillo Tech',
    'company': 'Zillo WebTech',
    'maintainer': 'Zillo WebTech',
    'website': 'https://www.nckwebtech.com/',
    'images': ['static/description/banner.png'],
    'depends': ['account', 'sale', 'sale_management', 'base', 'contacts'],
    'data': ['views/sale_tax_install_views.xml'],
    'demo': [],
    'installable': True,
    'application': True,
    'sequence': 10,
    'license': 'LGPL-3',
}
