{
    'name': 'Kansas Destination Tax',
    'version': '15.0.1.0.0',
    'summary': 'Kansas Destination Tax',
    'sequence': 10,
    'description': """""",
    'category': 'Accounting/Accounting',
    'author': 'Zillo Tech',
    'company': 'Zillo WebTech',
    'maintainer': 'Zillo WebTech',
    'website': 'https://www.nckwebtech.com/',
    'images': ['static/description/banner.png'],
    'depends': ['account', 'sale', 'sale_management', 'base', 'zillotech_usa_sale_tax_table', 'zillotech_usa_sale_tax_installation'],
    'data': ['views/sale_tax_inherit_views.xml'],
    'demo': [],
    'installable': True,
    'application': True,
    'sequence': 10,
    'license': 'LGPL-3',
}
